export default {
    START_GAME: 'START_GAME',
    PAUSE_GAME: 'PAUSE_GAME',
    RESUME_GAME: 'RESUME_GAME',
    QUIT_GAME: 'QUIT_GAME',

    START_LEVEL: 'START_LEVEL',

    PLACE_MOLE: 'PLACE_MOLE',
    CLEAR_MOLE: 'CLEAR_MOLE',

    SCHEDULE_STEP: 'SCHEDULE_STEP',
    TOGGLE_SOUND: 'TOGGLE_SOUND'
}
