export default {
    START_GAME: 'START_GAME',
    PAUSE_GAME: 'PAUSE_GAME',
    RESUME_GAME: 'RESUME_GAME',

    PLACE_MOLE: 'PLACE_MOLE',
    CLEAR_MOLE: 'CLEAR_MOLE',

    TOGGLE_SOUND: 'TOGGLE_SOUND'
}
