export default {
    START_GAME: 'START_GAME',
    PAUSE_GAME: 'PAUSE_GAME',
    RESUME_GAME: 'RESUME_GAME',
    QUIT_GAME: 'QUIT_GAME',

    START_LEVEL: 'START_LEVEL',

    BOP_MOLE: 'BOP_MOLE',

    TOGGLE_SOUND: 'TOGGLE_SOUND'
}
